apps/clientes/urls.py
# Django
from django.urls import include, path

# Views Dispositivos
from . import views

app_name = 'clientes'
urlpatterns = [

    # CAD_Clientes
    path('', views.clientes_index, name='clientes_index'),
    path('edit/<int:pk>', views.clientes_edit, name='clientes_edit'),
    path('add', views.clientes_add, name='clientes_add'),
    path('detail/<int:pk>', views.clientes_detail, name='clientes_detail'),
    path('delete/<int:pk>', views.clientes_delete, name='clientes_delete'),
]

apps/core/urls.py
# Django
from django.urls import path, include
from django.contrib.auth import views as auth_views

# Rest-Framework
from rest_framework.authtoken import views as rest_framework_views

# Views Core
from . import views

app_name = 'core'
urlpatterns = [

    #  Login / Logout
    path('sign-in/', views.login_user, name='sign-in'),
    path('sign-out/', views.logout_view, name='sign-out'),

    # Token Rest-Framework
    path('get_auth_token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
    path('rest-auth/', include('rest_auth.urls')),
]

apps/dispositivos/urls.py
# Django
from django.urls import include, path

# Views Dispositivos
from . import views

app_name = 'dispositivos'
urlpatterns = [

    # CAD_Dispositivos
    path('', views.dispositivos_index, name='dispositivos_index'),
    path('edit/<int:pk>', views.dispositivos_edit, name='dispositivos_edit'),
    path('add', views.dispositivos_add, name='dispositivos_add'),
    path('detail/<int:pk>', views.dispositivos_detail, name='dispositivos_detail'),
    path('delete/<int:pk>', views.dispositivos_delete, name='dispositivos_delete'),
]

apps/pdf/urls.py
# Django
from django.urls import path

# Views PDF
from .views import PdfOrdemServico

app_name = 'pdf'
urlpatterns = [

    path('generate/pdf/os/<int:pk>', PdfOrdemServico.as_view(), name='generate_pdf'),

]

apps/servicos/urls.py
# Django
from django.urls import include, path

# Views Servicos
from . import views

app_name = 'servicos'
urlpatterns = [

    # CAD_OS
    path('os/', views.ordemservicos_index, name='ordemservicos_index'),
    path('os/edit/<int:pk>', views.ordemservicos_edit, name='ordemservicos_edit'),
    path('os/add/', views.ordemservicos_add, name='ordemservicos_add'),
    path('os/detail/<int:pk>', views.ordemservicos_detail, name='ordemservicos_detail'),
    path('os/delete/<int:pk>', views.ordemservicos_delete, name='ordemservicos_delete'),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from apps.core import views as main_views
from ajax_select import urls as ajax_select_urls
from qr_code import urls as qr_code_urls
from apps.api.router import router


urlpatterns = [
    # Dashboard Principal
    path('', main_views.dashboard, name='dashboard'),

    # ADMIN: Apenas para administradores
    path('ediclei/', admin.site.urls),

    # APP: Core (Principal)
    path('core/', include('apps.core.urls')),

    # APPS: Local
    path('colaboradores/', include('apps.colaboradores.urls')),
    path('empregador/', include('apps.empregador.urls')),
    path('dispositivos/', include('apps.dispositivos.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('servicos/', include('apps.servicos.urls')),
    path('pdf/', include('apps.pdf.urls')),

    # API
    path('api/', include('apps.api.urls')),

    path('ajax_select/', include(ajax_select_urls)),
    path('qr_code/', include(qr_code_urls, namespace="qr_code")),


]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/core/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


# Classe controle token login rest-framework
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


# Classe controle de data/hora de criacao e modificacao.
class TimeStamped(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# Classe controle se foi visualizado ou nao.
class Displayable(models.Model):
    class Meta:
        abstract = True

    status = models.BooleanField(default=True)


#  ========================================= MODELO_PESSOA ===================================================
class Pessoa(TimeStamped, Displayable):
    pes_id = models.AutoField(db_column='pes_id', primary_key=True, unique=True, null=False, serialize=False)
    pes_nome = models.CharField(db_column='pes_nome', null=False, blank=False, max_length=80)
    pes_cpf = models.CharField(db_column='pes_cpf', null=True, blank=True, max_length=11)
    pes_rg = models.CharField(db_column='pes_rg', null=True, blank=True, max_length=20)
    pes_telefone = models.CharField(db_column='pes_telefone', null=True, blank=True, max_length=16)
    pes_celular = models.CharField(db_column='pes_celular', null=True, blank=True, max_length=17)
    pes_email = models.CharField(db_column='pes_email', null=True, blank=True, max_length=50)

    class Meta:
        ordering = ['-pes_id']
        db_table = 'PESSOAS'

    def __str__(self):
        return self.pes_nome

apps/dispositivos/models.py
# Django
from django.db import models

# Local
from apps.core.models import TimeStamped, Displayable
from .choices import MARCA_DISPOSITIVOS


#  ======================================== MODELO_CONTRATADO ================================================
class Dispositivo(TimeStamped, Displayable):
    #  basicas
    disp_id = models.AutoField(db_column='disp_id', auto_created=True, primary_key=True,
                               unique=True, null=False, serialize=False)
    marca = models.CharField(choices=MARCA_DISPOSITIVOS, max_length=3, db_column='marca')
    modelo = models.CharField(db_column='modelo', max_length=25)
    imei = models.CharField(db_column='imei', max_length=15, blank=True, null=True)
    url_img = models.ImageField(db_column='url_img', blank=True, upload_to='static/img/dispositivos/', null=True)
    cliente = models.ForeignKey('clientes.Cliente', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        ordering = ['-disp_id']
        db_table = 'DISPOSITIVOS'
        verbose_name = 'Dispositivo'
        verbose_name_plural = 'Dispositivos'

    def __str__(self):
        return self.modelo

apps/servicos/models.py
# Django
from django.utils.six import StringIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models

# Local
from apps.core.models import TimeStamped, Displayable
from .choices import ACESSORIOS_DISPOSITIVOS, TIPO_SERVICOS, STATUS

# Terceiros
from simple_history.models import HistoricalRecords
from multiselectfield import MultiSelectField
from djmoney.models.fields import MoneyField
import qrcode


#  ======================================== MODELO_ORDEM_SERVICO ================================================
class OrdemServico(TimeStamped, Displayable):
    #  basicas
    os_id = models.AutoField(db_column='os_id', auto_created=True, primary_key=True,
                             unique=True, null=False, serialize=False)
    acessorios = MultiSelectField(choices=ACESSORIOS_DISPOSITIVOS, max_choices=4,
                                  db_column='acessorios', null=True, blank=True)
    tipo_servico = models.CharField(choices=TIPO_SERVICOS, db_column='tipo_servico', max_length=2)
    descricao = models.CharField(blank=True, null=True, max_length=300, db_column='descricao')
    status = models.CharField(choices=STATUS, db_column='status', max_length=1)
    orcamento = MoneyField(db_column='orcamento', max_digits=10, decimal_places=2,
                           default_currency='BRL', null=True, default=0,
                           blank=True)
    hospedagem = models.CharField(db_column='hospedagem', null=True, blank=True, max_length=4)

    # terceiros
    historico = HistoricalRecords()

    # relacionamentos
    cliente = models.ForeignKey('clientes.Cliente', on_delete=models.SET_NULL,
                                null=True, related_name="clientes")
    dispositivos = models.ForeignKey('dispositivos.Dispositivo', on_delete=models.SET_NULL,
                                     null=True, related_name="dispositivos")

    FECHADA = "FECHADA"

    class Meta:
        ordering = ['-os_id']
        db_table = 'ORDEMSERVICO'
        verbose_name = 'Ordem de Serviço'
        verbose_name_plural = 'Ordens de Serviço'

    def __str__(self):
        return "O.S: #" + str(self.os_id)

apps/servicos/forms.py
# Django
from django import forms

# Local imports
from .models import OrdemServico
from apps.clientes.models import Cliente
from apps.dispositivos.models import Dispositivo
from .choices import STATUS, TIPO_SERVICOS, ACESSORIOS_DISPOSITIVOS

# terceiros
from djmoney.forms.fields import MoneyField


class OrdemServicoForm(forms.ModelForm):
    acessorios = forms.MultipleChoiceField(required=False, choices=ACESSORIOS_DISPOSITIVOS,
                                           widget=forms.CheckboxSelectMultiple())
    tipo_servico = forms.ChoiceField(choices=TIPO_SERVICOS, required=True)
    descricao = forms.CharField(required=False, max_length=300,
                                widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}))
    status = forms.ChoiceField(choices=STATUS, required=True)
    hospedagem = forms.CharField(required=False, max_length=4)

    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), empty_label="Selecione um cliente...",
                                     widget=forms.Select(attrs={'onchange': 'getDispositivo()'}))
    dispositivos = forms.ModelChoiceField(empty_label="<-----------", queryset=Dispositivo.objects.all())
    orcamento = MoneyField(required=False, default_amount=0, max_digits=10,
                           localize=True, decimal_places=2, default_currency='BRL')

    #  Uma classe inline para fornecer informações adicionais no formulário.
    class Meta:
        #  Fornecer uma associação entre ModelForm e um modelo
        model = OrdemServico
        fields = ('acessorios', 'tipo_servico', 'descricao', 'status',
                  'cliente', 'dispositivos', 'orcamento', 'hospedagem')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dispositivos'].queryset = Dispositivo.objects.none()

        if 'cliente' in self.data:
            try:
                cliente_id = int(self.data.get('cliente'))
                self.fields['dispositivos'].queryset = Dispositivo.objects.filter(cliente_id=cliente_id).order_by(
                    'modelo')
            except (ValueError, TypeError):
                pass  #
        elif self.instance.pk:
            self.fields['dispositivos'].queryset = self.instance.cliente.dispositivo_set.order_by('modelo')

apps/core/views.py
#  Django
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render, redirect

# local
from apps.servicos.models import OrdemServico

#  Terceiros
import sweetify


#  DASHBOARD_PRINCIPAL ===============================================================================
@login_required(login_url='/core/sign-in/')
def dashboard(request):
    storage = messages.get_messages(request)
    user = getattr(request, 'user', None)

    hoje = datetime.date.today()

    os_abertas = OrdemServico.objects.filter(Q(status=1)).count()
    os_prontas = OrdemServico.objects.filter(Q(status=8)).count()
    os_entregues = OrdemServico.objects.filter(Q(status=9)).count()
    os_atrasadas = OrdemServico.objects.filter(created_at__day=-30 + hoje.day).count()

    args = {'user': user, 'message': storage, 'os_abertas': os_abertas,
            'os_prontas': os_prontas, 'os_atradadas': os_atrasadas, 'os_entregues': os_entregues}
    return render(request, 'core/dashboard.html', args)


#  ===================================================================================================


#  LOGIN_USER =======================================================================================
def login_user(request):
    if not request.method == 'POST':
        return render(request, 'core/sign_in.html')
    user = authenticate(username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect('/')
    sweetify.error(request, 'Usuário ou Senha inválidos!', persistent='OK')
    return render(request, 'core/sign_in.html')
#  ===================================================================================================


#  LOGOUT_USER =======================================================================================
def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return render(request, 'core/sign_in.html')
#  ===================================================================================================

apps/servicos/views.py
# Django imports
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone

# Local
from qr_code.qrcode.serve import make_qr_code_url
from qr_code.qrcode.utils import QRCodeOptions
from .utils import abbreviate

from apps.clientes.models import Cliente
from .models import OrdemServico
from .forms import OrdemServicoForm
from apps.dispositivos.models import Dispositivo

# Terceiros
import sweetify


# ORDEM_SERVICO_ADD =======================================================================================
@login_required(login_url='/core/sign-in/')
def ordemservicos_add(request):
    if request.method == 'POST':
        form = OrdemServicoForm(request.POST or None)
        if not form.is_valid():
            sweetify.error(request, 'Ha algum erro no preenchimento dos campos!', persistent='OK')
            return render(request, 'servicos/os/os_add.html', {'form': form})
        model_instance = form.save(commit=False)
        model_instance.timestamp = timezone.now()
        model_instance.save()
        sweetify.success(request, 'Ordem de Serviço criada com sucesso!')
        return HttpResponseRedirect(reverse('servicos:ordemservicos_detail', args=(model_instance.pk,)))
    else:
        form = OrdemServicoForm()
        return render(request, 'servicos/os/os_add.html', {'form': form})


# ORDEM_SERVICO_EDIT =======================================================================================
@login_required(login_url='/core/sign-in/')
def ordemservicos_edit(request, pk):
    ordemservico = get_object_or_404(OrdemServico, pk=pk)

    if request.method == "POST":
        form = OrdemServicoForm(request.POST, instance=ordemservico)
        if not form.is_valid():
            sweetify.error(request, 'Ha algum erro no preenchimento dos campos!', persistent='OK')
            return render(request, 'servicos/os/os_edit.html', {'form': form})
        ordemservico = form.save(commit=False)
        ordemservico.timestamp = timezone.now()
        ordemservico.save()
        sweetify.success(request, 'Editado com Sucesso!')
        return HttpResponseRedirect(reverse('servicos:ordemservicos_detail', args=(ordemservico.pk,)))
    else:
        form = OrdemServicoForm(instance=ordemservico)

    args = {'form': form, 'ordemservico': ordemservico}
    return render(request, 'servicos/os/os_edit.html', args)


# ORDEM_SERVICO_DELETE ======================================================================================
def ordemservicos_delete(request, pk):
    dispositivo = get_object_or_404(OrdemServico, pk=pk)
    dispositivo.delete()
    sweetify.success(request, 'O.S deletada com sucesso!')

    return redirect('/servicos/os')


# ORDEM_SERVICO_DETAIL ======================================================================================
@login_required(login_url='/core/sign-in/')
def ordemservicos_detail(request, pk):
    msg = messages.get_messages(request)
    ordemservico = get_object_or_404(OrdemServico, pk=pk)

    options_qr = QRCodeOptions(size='t', border=6, error_correction='L')
    qr_url = make_qr_code_url("URL:https://excelencia.online/c/" + str(ordemservico.os_id),
                              qr_code_options=options_qr)

    args = {'ordemservico': ordemservico, 'qr_url': qr_url,  'message': msg}
    return render(request, 'servicos/os/os_detail.html', args)


# ORDEM_SERVICO_INDEX =======================================================================================
@login_required(login_url='/core/sign-in/')
def ordemservicos_index(request):
    user = getattr(request, 'user', None)
    os_list = OrdemServico.objects.select_related('cliente', 'dispositivos').exclude(status=9)

    paginator = Paginator(os_list, 4)  # Exibir 10 objetos por pagina

    page = request.GET.get('page')

    try:
        ordensservico = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        ordensservico = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        ordensservico = paginator.page(paginator.num_pages)

    args = {'ordensservico': ordensservico, 'user': user}
    return render(request, 'servicos/os/os_list.html', args)

apps/core/templates/servicos/os/dispositivos_dropdown_list.html
<option value="">---------</option>
{% for dispositivo in dispositivos %}
<option value="{{ dispositivo.pk }}">{{ dispositivo.modelo }}</option>
{% endfor %}

apps/core/templates/servicos/os/os_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load core_tags %}
{% load qr_code %}

{% block titulo %}
    <h4 class="title semibold">O.S #{{ ordemservico.os_id }}</h4>
{% endblock %}

{% block toolbar %}
    <div class="toolbar">
        <ol class="breadcrumb breadcrumb-transparent nm">
            <li><a href="/">Desktop</a></li>
            <li><a href="{% url 'servicos:ordemservicos_index' %}">Ordem Serviço</a></li>
            <li class="active">Detalhes</li>
        </ol>
    </div>
{% endblock %}

{% block content %}

    <!-- Page Header -->
    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked">
                <li>
                    <a href="{% url 'clientes:clientes_index' %}">Clientes</a>
                </li>
                <li>
                    <a href="{% url 'dispositivos:dispositivos_index' %}">Dispositivos</a>
                </li>
            </ul>
        </div>
        <div class="col-md-9">
            <div >

                <section class="content content_content" style="width: 100%; margin: auto;">
                    <section class="invoice">
                        <!-- title row -->
                        <div class="row">
                            <div class="col-xs-12">
                                <h2 class="page-header">
                                    <i class="fa fa-globe"></i> {{ ordemservico.cliente.pes_nome|abreviar:"False" }}
                                    <small class="pull-right">Data: {{ ordemservico.created_at|date:'d/m/y' }}</small>
                                </h2>
                            </div><!-- /.col -->
                        </div>
                        <!-- info row -->
                        <div class="row invoice-info">

                            <div class="col-sm-4 invoice-col" align="left">
                                <div>
                                       CPF:
                                    <p class="cpf">{{ ordemservico.cliente.pes_cpf }}</p>
                                    Celular:
                                    <p class="celular"><a href="tel:{{ ordemservico.cliente.pes_celular }}">{{ ordemservico.cliente.pes_celular }}</a></p>
                                </div>
                            </div><!-- /.col -->
                            <div class="col-sm-4 invoice-col" align="center">
                            </div>
                            <div class="col-sm-4 invoice-col" align="right">
                                <b>O.S #{{ ordemservico.os_id }}</b><br>
                                <b>Hora: {{ ordemservico.created_at|date:'H:i' }}</b>
                                <br><br>
                                <b>Aberta por:</b><br>
                                <b></b><br>

                            </div><!-- /.col -->
                        </div><!-- /.row -->

                        <!-- Table row -->
                        <div class="row">
                            <div class="col-xs-12 table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Marca</th>
                                        <th>Modelo</th>
                                        <th>IMEI</th>
                                    </tr>
                                    </thead>
                                    <tbody>


                                    <tr>
                                        <td>{{ ordemservico.dispositivos.get_marca_display }}</td>
                                        <td>{{ ordemservico.dispositivos.modelo|upper }}</td>
                                        <td>{{ ordemservico.dispositivos.imei }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div><!-- /.col -->
                        </div><!-- /.row -->

                         <!-- Table row -->
                        <div class="row">
                            <div class="col-xs-12 table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Tipo de serviço</th>
                                        <th>Observação</th>
                                    </tr>
                                    </thead>
                                    <tbody>


                                    <tr>
                                        <td>{{ ordemservico.get_tipo_servico_display }}</td>
                                        <td>
                                            {% if ordemservico.descricao == isnull %}
                                                sem observações.
                                            {% else %}
                                                {{ ordemservico.descricao }}
                                            {% endif %}
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div><!-- /.col -->
                        </div><!-- /.row -->

                     <!-- Table row -->
                        <div class="row">
                            <div class="col-xs-12 table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Acessórios (itens junto ao dispositivo)</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>


                                    <tr>
                                        <td>{% if ordemservico.acessorios == isnull %}
                                                nenhum acessório.
                                            {% else %}
                                                {{ ordemservico.acessorios|lower }}
                                            {% endif %}
                                        </td>
                                        <td>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div><!-- /.col -->
                        </div><!-- /.row -->
                        <br>

                        <div class="row">
                            <!-- accepted payments column -->
                            <div class="col-md-12">
                                            {% if ordemservico.status != 8 and ordemservico.status != 9  %}
                                                <p class="lead text-danger"><strong class="text-info">Status:</strong> {{ ordemservico.get_status_display }}</p>
                                            {% else %}
                                                <p class="lead text-success"><strong class="text-info">Status:</strong> {{ ordemservico.get_status_display }}</p>
                                            {% endif %}
                                <p class="text-center">
                                    <img width="128px" src="{{ qr_url }}" alt="QRCode"></p>

                                <div class="table-responsive">
                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <th>Orçamento:</th>
                                            <th>{{ ordemservico.orcamento }}</th>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <br>
                                </div>
                            </div><!-- /.col -->
                        </div><!-- /.row -->

                        <!-- this row will not appear when printing -->
                        <div class="row no-print">
                            <div class="col-xs-12">
                                <a href="{% url 'pdf:generate_pdf' pk=ordemservico.pk %}" target="_blank" id="trigger" class="btn btn-default"><i class="fa fa-print"></i> Imprimir</a>
                                <button class="btn btn-success pull-right"><i class="fa fa-credit-card"></i> Encerrar
                                </button>
                                <a href="{% url 'servicos:ordemservicos_edit' pk=ordemservico.pk %}" class="btn btn-primary pull-right" style="margin-right: 5px;"><i
                                        class="fa fa-download"></i> Editar
                                </a>
                            </div>
                        </div>
                    </section>
                </section>

            </div>
            <div class="content content_content" style="width: 100%; align-content: center; align-items: center; margin: auto;">
                <div class="panel-heading">
                    <h4 class="panel-title panel-title-mini">Histórico</h4>
                    <div class="panel-toolbar text-right">

                    </div>
                </div>
                <div class="table-responsive invoice">
                    <table class="table table-stripped table-hover">
                        <thead>
                        <tr>
                            <th class="col-table-1">Data/Hora</th>
                            <th class="col-table-1">Ação</th>
                            <th class="col-table-1">Status</th>
                            <th class="col-table-6">Descrição</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ ordemservico.updated_at|date:'d/m/y H:i'}}</td>
                            <td></td>
                            <td>{{ ordemservico.historico.get_history_user }}</td>
                            <td>Aparelho com tela trincada. Muitos arranhões. Sem carregador.</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <!-- Modal Delete -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Confirmação</h4>
                </div>
                <div class="modal-body">
                    <h4>Tem certeza que deseja deletar a ordem d serviço???</h4><br>
                    <h4>ID: {{ ordemservico.pk }}</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a id="btn-excluir"
                       class="btn btn-danger"
                       href="{% url 'servicos:ordemservicos_delete' pk=ordemservico.pk %}">Deletar</a>
                </div>
            </div>
        </div>
    </div>
    <!-- ...Modal Delete -->



{% endblock %}

{% block javascript %}

     <script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>

    <script>
        $('.dinheiro').mask('#.##0,00', {reverse: true});
        $('.telefone').mask('(00) 0000-0000');
        $('.celular').mask('(00) 0 0000-0000');
        $('.cpf').mask('000.000.000-00');
    </script>


{% endblock %}