apps/clientes/urls.py
# Django
from django.urls import include, path

# Views Dispositivos
from . import views

app_name = 'clientes'
urlpatterns = [

    # CAD_Clientes
    path('', views.clientes_index, name='clientes_index'),
    path('edit/<int:pk>', views.clientes_edit, name='clientes_edit'),
    path('add', views.clientes_add, name='clientes_add'),
    path('detail/<int:pk>', views.clientes_detail, name='clientes_detail'),
    path('delete/<int:pk>', views.clientes_delete, name='clientes_delete'),
]

apps/colaboradores/urls.py
# Django
from django.urls import include, path

# Views Cadastro
from . import views

app_name = 'colaboradores'
urlpatterns = [

    # CAD_CONTRATADO
    path('contratados/', views.contratado_index, name='contratado_index'),
    path('contratados/edit/<int:pk>', views.contratado_edit, name='contratado_edit'),
    path('contratados/add', views.contratado_add, name='contratado_add'),
    path('contratados/detail/<int:pk>', views.contratado_detail, name='contratado_detail'),
]

apps/core/urls.py
# Django
from django.urls import path, include
from django.contrib.auth import views as auth_views

# Rest-Framework
from rest_framework.authtoken import views as rest_framework_views

# Views Core
from . import views

app_name = 'core'
urlpatterns = [

    #  Login / Logout
    path('sign-in/', views.login_user, name='sign-in'),
    path('sign-out/', views.logout_view, name='sign-out'),

    # Token Rest-Framework
    path('get_auth_token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
    path('rest-auth/', include('rest_auth.urls')),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from apps.core import views as main_views
from ajax_select import urls as ajax_select_urls
from qr_code import urls as qr_code_urls
from apps.api.router import router


urlpatterns = [
    # Dashboard Principal
    path('', main_views.dashboard, name='dashboard'),

    # ADMIN: Apenas para administradores
    path('ediclei/', admin.site.urls),

    # APP: Core (Principal)
    path('core/', include('apps.core.urls')),

    # APPS: Local
    path('colaboradores/', include('apps.colaboradores.urls')),
    path('empregador/', include('apps.empregador.urls')),
    path('dispositivos/', include('apps.dispositivos.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('servicos/', include('apps.servicos.urls')),
    path('pdf/', include('apps.pdf.urls')),

    # API
    path('api/', include('apps.api.urls')),

    path('ajax_select/', include(ajax_select_urls)),
    path('qr_code/', include(qr_code_urls, namespace="qr_code")),


]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/colaboradores/models.py
# Django
from django.db import models

# Local
from djmoney.models.fields import MoneyField
from apps.core.models import Pessoa, TimeStamped, Displayable
from .choices import *


#  ======================================== MODELO_CONTRATADO ================================================
class Contratado(Pessoa):
    #  basicas
    con_matricula = models.CharField(db_column='con_matricula', primary_key=True, max_length=30)
    estabelecimento = models.ForeignKey('empregador.Estabelecimento', on_delete=models.CASCADE)
    lotacao = models.ForeignKey('empregador.Lotacao', on_delete=models.CASCADE)
    funcao = models.ForeignKey('empregador.Funcao', on_delete=models.CASCADE)
    sindicato = models.ForeignKey('empregador.Sindicato', on_delete=models.CASCADE)

    #  trabalhistas
    con_tipo_reg_trabalhista = models.CharField(max_length=3, choices=TIPO_REGIME_TRABALHISTA,
                                                db_column='con_tipo_reg_trabalhista')
    con_tipo_reg_previdenciario = models.CharField(max_length=4, choices=TIPO_REGIME_PREVIDENCIARIO,
                                                   db_column='con_tipo_reg_previdenciario')
    con_regime_jornada = models.CharField(max_length=1, choices=REGIME_DE_JORNADA,
                                          db_column='con_regime_jornada')
    con_natureza_atividade = models.CharField(max_length=1, choices=NATUREZA_DA_ATIVIDADE,
                                              db_column='con_natureza_atividade')
    con_categoria = models.CharField(max_length=1, choices=CATEGORIA, db_column='con_categoria')

    #  info_contrato
    con_data_admissao = models.DateField(db_column='con_data_admissao', null=True, blank=True)
    con_tipo_contrato = models.CharField(db_column='con_tipo_contrato', max_length=1,
                                         blank=True, null=True, choices=TIPO_CONTRATO_TRABALHO)
    con_tipo_admissao = models.CharField(db_column='con_tipo_admissao', max_length=1,
                                         blank=True, null=True, choices=TIPO_ADMISSAO, default='A')
    con_unidade_salario = models.CharField(db_column='con_unidade_salario', max_length=1,
                                           choices=UNIDADE_SALARIO, default='M')
    con_indicativo_admissao = models.CharField(db_column='con_indicativo_admissao', max_length=1,
                                               choices=INDICATIVO_ADMISSAO, default='N')
    con_salario_mensal = MoneyField(db_column='con_salario_mensal', max_digits=10, decimal_places=2,
                                    default_currency='BRL', null=True,
                                    blank=True)
    con_calcular_dsr = models.BooleanField(db_column='con_calcular_dsr', default=True)
    con_receber_fgts = models.BooleanField(db_column='con_receber_fgts', default=True)

    #  outra empresa
    con_vinculo_outra_empresa = models.CharField(max_length=1, db_column='con_vinculo_outra_empresa',
                                                 null=True, blank=True, choices=VINCULO_COM_OUTRA_EMPRESA)
    con_cnpj_outra_empresa = models.CharField(max_length=14, db_column='con_cnjp_outra_empresa', null=True, blank=True)
    con_remuneracao_outra_empresa = MoneyField(db_column='con_remuneracao_outra_empresa', max_digits=10,
                                               decimal_places=2, default_currency='BRL', null=True, blank=True)

    class Meta:
        ordering = ['-con_matricula']
        db_table = 'CONTRATADOS'
        verbose_name = 'Contratado'
        verbose_name_plural = 'Contratados'

    def __str__(self):
        return self.pes_nome


class PessoaResumo(Pessoa):
    class Meta:
        proxy = True
        verbose_name = 'Pessoa Resumo'
        verbose_name_plural = 'Resumo de Pessoas'

apps/core/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


# Classe controle token login rest-framework
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


# Classe controle de data/hora de criacao e modificacao.
class TimeStamped(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# Classe controle se foi visualizado ou nao.
class Displayable(models.Model):
    class Meta:
        abstract = True

    status = models.BooleanField(default=True)


#  ========================================= MODELO_PESSOA ===================================================
class Pessoa(TimeStamped, Displayable):
    pes_id = models.AutoField(db_column='pes_id', primary_key=True, unique=True, null=False, serialize=False)
    pes_nome = models.CharField(db_column='pes_nome', null=False, blank=False, max_length=80)
    pes_cpf = models.CharField(db_column='pes_cpf', null=True, blank=True, max_length=11)
    pes_rg = models.CharField(db_column='pes_rg', null=True, blank=True, max_length=20)
    pes_telefone = models.CharField(db_column='pes_telefone', null=True, blank=True, max_length=16)
    pes_celular = models.CharField(db_column='pes_celular', null=True, blank=True, max_length=17)
    pes_email = models.CharField(db_column='pes_email', null=True, blank=True, max_length=50)

    class Meta:
        ordering = ['-pes_id']
        db_table = 'PESSOAS'

    def __str__(self):
        return self.pes_nome

apps/colaboradores/forms.py
# Django
from django import forms

# Local imports
from .models import Contratado
from apps.empregador.models import Estabelecimento, Lotacao, Funcao, Sindicato


class ContratadoForm(forms.ModelForm):
    pes_nome = forms.CharField(required=True, max_length=80,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    pes_email = forms.EmailField(required=False, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    con_matricula = forms.CharField(required=True, max_length=30, min_length=3,
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))
    estabelecimento = forms.ModelChoiceField(queryset=Estabelecimento.objects.all(),
                                             empty_label="----------")
    lotacao = forms.ModelChoiceField(queryset=Lotacao.objects.all(), empty_label="----------")
    funcao = forms.ModelChoiceField(queryset=Funcao.objects.all(), empty_label="----------")
    sindicato = forms.ModelChoiceField(queryset=Sindicato.objects.all(), empty_label="----------")

    #  Uma classe inline para fornecer informações adicionais no formulário.
    class Meta:
        #  Fornecer uma associação entre ModelForm e um modelo
        model = Contratado
        fields = ('pes_nome', 'pes_email', 'con_matricula',
                  'estabelecimento', 'lotacao', 'funcao',
                  'sindicato')

apps/colaboradores/views.py
# Django imports
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone

# Local
from .models import Contratado
from .forms import ContratadoForm

# Terceiros
import sweetify


# CONTRATADO_ADD =======================================================================================
@login_required(login_url='/core/sign-in/')
def contratado_add(request):
    if request.method == 'POST':
        form = ContratadoForm(request.POST or None)
        if not form.is_valid():
            sweetify.error(request, 'Ha algum erro no preenchimento dos campos!', persistent='OK')
            return render(request, 'colaboradores/contratados/contratado_add.html', {'form': form})
        model_instance = form.save(commit=False)
        model_instance.timestamp = timezone.now()
        model_instance.save()
        sweetify.success(request, 'Funcionario cadastrado com sucesso!')
        return HttpResponseRedirect(reverse('colaboradores:contratado_detail', args=(model_instance.pk,)))
    else:
        form = ContratadoForm()
        return render(request, 'colaboradores/contratados/contratado_add.html', {'form': form})


# CONTRATADO_EDIT =======================================================================================
@login_required(login_url='/core/sign-in/')
def contratado_edit(request, pk):
    contratado = get_object_or_404(Contratado, pk=pk)
    if request.method == "POST":
        form = ContratadoForm(request.POST, instance=contratado)
        if not form.is_valid():
            sweetify.error(request, 'Ha algum erro no preenchimento dos campos!', persistent='OK')
            return render(request, 'colaboradores/contratados/contratado_edit.html', {'form': form})
        contratado = form.save(commit=False)
        contratado.timestamp = timezone.now()
        contratado.save()
        sweetify.success(request, 'Editado com Sucesso!')
        return HttpResponseRedirect(reverse('colaboradores:contratado_detail', args=(contratado.pk,)))
    else:
        form = ContratadoForm(instance=contratado)

    args = {'form': form, 'contratados': contratado}
    return render(request, 'colaboradores/contratados/contratado_edit.html', args)


# CONTRATADO_DELETE ======================================================================================
def contratado_delete(request, pk):
    contratado = Contratado.objects.filter(pk=pk)
    contratado.delete()
    return redirect("contratado_index")


# CONTRATADO_DETAIL ======================================================================================
@login_required(login_url='/core/sign-in/')
def contratado_detail(request, pk):
    msg = messages.get_messages(request)
    contratado = get_object_or_404(Contratado, pk=pk)

    args = {'contratado': contratado, 'message': msg}
    return render(request, 'colaboradores/contratados/contratado_detail.html', args)


# CONTRATADO_INDEX =======================================================================================
@login_required(login_url='/core/sign-in/')
def contratado_index(request):
    user = getattr(request, 'user', None)
    pes_list = Contratado.objects.all()
    paginator = Paginator(pes_list, 10)  # Exibir 10 objetos por pagina

    page = request.GET.get('page')
    try:
        contratados = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contratados = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contratados = paginator.page(paginator.num_pages)

    return render(request, 'colaboradores/contratados/contratado_list.html', {'contratados': contratados, 'user': user})

apps/core/views.py
#  Django
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render, redirect

# local
from apps.servicos.models import OrdemServico

#  Terceiros
import sweetify


#  DASHBOARD_PRINCIPAL ===============================================================================
@login_required(login_url='/core/sign-in/')
def dashboard(request):
    storage = messages.get_messages(request)
    user = getattr(request, 'user', None)

    hoje = datetime.date.today()

    os_abertas = OrdemServico.objects.filter(Q(status=1)).count()
    os_prontas = OrdemServico.objects.filter(Q(status=8)).count()
    os_entregues = OrdemServico.objects.filter(Q(status=9)).count()
    os_atrasadas = OrdemServico.objects.filter(created_at__day=-30 + hoje.day).count()

    args = {'user': user, 'message': storage, 'os_abertas': os_abertas,
            'os_prontas': os_prontas, 'os_atradadas': os_atrasadas, 'os_entregues': os_entregues}
    return render(request, 'core/dashboard.html', args)


#  ===================================================================================================


#  LOGIN_USER =======================================================================================
def login_user(request):
    if not request.method == 'POST':
        return render(request, 'core/sign_in.html')
    user = authenticate(username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect('/')
    sweetify.error(request, 'Usuário ou Senha inválidos!', persistent='OK')
    return render(request, 'core/sign_in.html')
#  ===================================================================================================


#  LOGOUT_USER =======================================================================================
def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return render(request, 'core/sign_in.html')
#  ===================================================================================================

apps/core/templates/colaboradores/contratados/contratado_add.html
{% extends 'core/base.html' %}
{% load core_tags %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    <h4 class="topbar-title">Add Contratado</h4>
{% endblock %}

{% block content %}

                <div class="row">
                    <div class="col-md-2">
                  		<ul class="nav nav-pills nav-stacked">
                  			<li>
                  				<a href="{% url 'colaboradores:contratado_index' %}">Contratados</a>
                  			</li>
                  			<li>
                  				<a href="#">Diretores</a>
                  			</li>
                  			<li>
                  				<a href="#">Estagiários</a>
                  			</li>
                  		</ul>
                    </div>

                    <div class="col-md-9">

                    	<form class="form-horizontal panel panel-inverse" accept-charset="ISO-8859-1" method="post">
                    	{% csrf_token %}
                    		<div class="panel-heading">
                    	  		<h3 class="panel-title">Informações básicas</h3>
                    	  	</div>


                    	  <div class="panel-body">
                    	  		<input type="hidden" id="id" name="id" value="">
                    	  		<div class="form-group">
                    	  			<label class="control-label col-sm-4">Nome*</label>
                    	  			<div class="col-sm-6">
                    	  				{{ form.pes_nome }}
                    	  			</div>
                    	  		</div>
                    	  		<div class="form-group">
                    	  			<label class="control-label col-sm-4">Matrícula*</label>
                    	  			<div class="col-sm-6">
                    	  				{{ form.con_matricula }}
                    	  			</div>
                    	  		</div>
                    	  	 	<div class="form-group">
                   	  				<label class="control-label col-sm-4">Email</label>
                   	  				<div class="col-sm-6">
                   	  					{{ form.pes_email }}
                   	  				</div>
                   	  			</div>
                    	  		<div class="form-group">
                    	  			<label class="control-label col-sm-4">Estabelecimento</label>
                    	  			<div class="col-sm-6">
                    	  				{{ form.estabelecimento|addcss:"form-control" }}
                    	  			</div>
                    	  		</div>
                    	  		<div class="form-group">
                    	  			<label class="control-label col-sm-4">Lotação*</label>
                    	  			<div class="col-sm-4">
                    	  				{{ form.lotacao|addcss:"form-control" }}
                    	  			</div>
                    	  			<div class="col-sm-2">
                    	  				<a href="#" id="cadastraLotacaoBt">Cadastrar lotação básica</a>
                    	  			</div>
                    	  		</div>
                    	  		<div class="form-group">
                    	  			<label class="control-label col-sm-4">Função*</label>
                    	  			<div class="col-sm-4">
                    	  				{{ form.funcao|addcss:"form-control" }}
                    	  			</div>
                    	  			<div class="col-sm-2">
                    	  				<a href="#" id="cadastraFuncaoBt">Cadastrar nova</a>
                    	  			</div>
                    	  		</div>
                    	  		<div class="form-group">
                    	  			<label class="control-label col-sm-4">Sindicato</label>
                    	  			<div class="col-sm-4">
                    	  				{{ form.sindicato|addcss:"form-control" }}
                    	  			</div>
                    	  			<div class="col-sm-2">
                    	  				<a href="#" id="cadastraSindicatoBt">Cadastrar novo</a>
                    	  			</div>
                    	  		</div>
                    	  	</div>


                    	  	<div class="panel-footer">
                    	  		<input type="submit" class="btn btn-primary" value="Salvar e continuar" id="salvar" data-loading-text="Processando...">
                    	  		<a href="{% url 'colaboradores:contratado_index' %}">Cancelar</a>
                    	  	</div>
						</form>
					</div>
			    </div>


{% endblock %}

apps/core/templates/colaboradores/contratados/contratado_detail.html
{% extends 'core/base.html' %}

{% block content %}

    <!-- Page Header -->
    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked">
                <li>
                    <a href="{% url 'clientes:clientes_index' %}">Clientes</a>
                </li>
                <li>
                    <a href="#">Dispositivos</a>
                </li>
                <li>
                    <a href="#">Ordem Serviço</a>
                </li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title ellipsis">{{ contratado.pes_nome }}</h3>
                    <div class="panel-toolbar text-right">
                        <a class="btn btn-default" href="{% url 'colaboradores:contratado_edit' pk=cliente.pk %}"><span
                                class="ico-pencil6"></span> Editar</a>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Mais
                                <span class="caret"></span></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a id="bt-registro" href="javascript:void(0);">Ficha de Registro</a></li>
                                <li>
                                    <a href="#">
                                        <span class="text">Dependentes</span>
                                        <span class="number">
		                    							<span class="label label-success">0</span>
		                    						</span>
                                    </a>
                                </li>
                                <li><a id="bt-opces" href="#">Opções Adicionais</a></li>
                                <li><a id="bt-opces" href="#">Histórico de
                                    Funções</a></li>
                                <li><a id="bt-opces" href="#">Transferências</a></li>
                                <li><a id="bt-arquivos" href="#">Anexos</a></li>
                            </ul>
                        </div>
                        <a id="btn-excluir" class="btn btn-danger" data-confirm="Tem certeza, que deseja deletar: {{ contratado.pes_nome }} ???"
                           href="#"><span class="ico-trash"></span> Deletar</a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tbody class="visualizacao-corpo">
                        <tr>
                            <td>Matrícula</td>
                            <td>{{ contratado.con_matricula }}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>{{ contratado.pes_email }}</td>
                        </tr>
                        <tr>
                            <td>Estabelecimento</td>
                            <td>{{ contratado.estabelecimento }}</td>
                        </tr>
                        <tr>
                            <td>Lotação</td>
                            <td>{{ contratado.lotacao }}</td>
                        </tr>
                        <tr>
                            <td>Função</td>
                            <td>{{ contratado.funcao }}</td>
                        </tr>
                        <tr>
                            <td>Sindicato</td>
                            <td>{{ contratado.sindicato }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title panel-title-mini">Informações do Trabalho</h4>
                    <div class="panel-toolbar text-right">
                        <a class="btn btn-default" href="#"><span
                                class="ico-pencil6"></span> Editar</a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tbody class="visualizacao-corpo">
                        <tr>
                            <td>Tipo de regime trabalhista</td>
                            <td>{{ contratado.con_tipo_reg_trabalhista }}</td>
                        </tr>
                        <tr>
                            <td>Tipo de regime previdenciário</td>
                            <td>{{ contratado.get_con_tipo_reg_previdenciario_display }}</td>
                        </tr>
                        <tr>
                            <td>Regime de jornada</td>
                            <td>{{ contratado.get_con_regime_jornada_display }}</td>
                        </tr>
                        <tr>
                            <td>Natureza da atividade</td>
                            <td>{{ contratado.get_con_natureza_atividade_display }}</td>
                        </tr>
                        <tr>
                            <td>Data base da categoria</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Categoria</td>
                            <td>{{ contratado.get_con_categoria_display }}</td>
                        </tr>
                        <tr>
                            <td>Vínculo com outra empresa</td>
                            <td>{% if contratado.get_con_vinculo_outra_empresa_display == None %} Não Informado{% else %}{{contratado.con_salario_mensal}}{% endif %}</td>
                        </tr>


                        </tbody>
                    </table>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title panel-title-mini">Informações do Contrato</h4>
                    <div class="panel-toolbar text-right">
                        <a class="btn btn-default" href="#"><span
                                class="ico-pencil6"></span> Editar</a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tbody class="visualizacao-corpo">
                        <tr>
                            <td>Data de admissão</td>
                            <td>{% if contratado.con_data_admissao == None %}Não Definida{% else %} {{ contratado.con_data_admissao }}{% endif %}</td>
                        </tr>
                        <tr>
                            <td>Tipo de contrato de trabalho</td>
                            <td>{% if contratado.get_con_tipo_contrato_display == None %}Não Definido{% else %} {{ contratado.get_con_tipo_contrato_display }} {% endif %}</td>
                        </tr>


                        <tr>
                            <td>Tipo de admissão</td>
                            <td>{{ contratado.get_con_tipo_admissao_display }}</td>
                        </tr>
                        <tr>
                            <td>Indicativo de admissão</td>
                            <td>{{ contratado.get_con_indicativo_admissao_display }}</td>
                        </tr>
                        <tr>
                            <td>Unidade de salário</td>
                            <td>{{ contratado.get_con_unidade_salario_display }}</td>
                        </tr>
                        <tr>
                            <td>Valor Por Mês</td>

                            <td>{% if contratado.con_salario_mensal == None %}R$ 0,0{% else %}{{contratado.con_salario_mensal}}{% endif %}</td>
                        </tr>
                        <tr>
                            <td>Calcular DSR</td>
                            <td>{% if contratado.con_calcular_dsr == True %}Sim{% else %}Não{% endif %}</td>
                        </tr>
                        <tr>
                            <td>Recebe FGTS</td>
                            <td>{% if contratado.con_receber_fgts == True %}Sim{% else %}Não{% endif %}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title panel-title-mini">Quadro de horários</h4>
                    <div class="panel-toolbar text-right">
                        <a class="btn btn-default" href="#"><span
                                class="ico-pencil6"></span> Editar</a>
                    </div>
                </div>
                <div class="table-responsive" id="tbTurnosAssociados">
                    <table class="table table-stripped table-hover">
                        <thead>
                        <tr>
                            <th>
                            <th>Código</th>
                            <th>Hr entrada</th>
                            <th>Hr saída</th>
                            <th>Duração</th>
                            <th>Intervalo</th>
                            <th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                        <tbody class="visualizacao-corpo">
                        <tr>
                            <td>Tipo de Jornada</td>
                            <td colspan="5">Jornada Semanal</td>
                        </tr>
                        <tr>
                            <td>Carga semanal em horas</td>
                            <td colspan="5">00:00</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block javascript %}
  <script>
    $(document).on('click', ':not(form)[data-confirm]', function(e){
      if(!confirm($(this).data('confirm'))){
          e.stopImmediatePropagation();
          e.preventDefault();
      }
    });
  </script>
{% endblock %}