apps/clientes/urls.py
# Django
from django.urls import include, path

# Views Dispositivos
from . import views

app_name = 'clientes'
urlpatterns = [

    # CAD_Clientes
    path('', views.clientes_index, name='clientes_index'),
    path('edit/<int:pk>', views.clientes_edit, name='clientes_edit'),
    path('add', views.clientes_add, name='clientes_add'),
    path('detail/<int:pk>', views.clientes_detail, name='clientes_detail'),
    path('delete/<int:pk>', views.clientes_delete, name='clientes_delete'),
]

apps/core/urls.py
# Django
from django.urls import path, include
from django.contrib.auth import views as auth_views

# Rest-Framework
from rest_framework.authtoken import views as rest_framework_views

# Views Core
from . import views

app_name = 'core'
urlpatterns = [

    #  Login / Logout
    path('sign-in/', views.login_user, name='sign-in'),
    path('sign-out/', views.logout_view, name='sign-out'),

    # Token Rest-Framework
    path('get_auth_token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
    path('rest-auth/', include('rest_auth.urls')),
]

apps/dispositivos/urls.py
# Django
from django.urls import include, path

# Views Dispositivos
from . import views

app_name = 'dispositivos'
urlpatterns = [

    # CAD_Dispositivos
    path('', views.dispositivos_index, name='dispositivos_index'),
    path('edit/<int:pk>', views.dispositivos_edit, name='dispositivos_edit'),
    path('add', views.dispositivos_add, name='dispositivos_add'),
    path('detail/<int:pk>', views.dispositivos_detail, name='dispositivos_detail'),
    path('delete/<int:pk>', views.dispositivos_delete, name='dispositivos_delete'),
]

apps/servicos/urls.py
# Django
from django.urls import include, path

# Views Servicos
from . import views

app_name = 'servicos'
urlpatterns = [

    # CAD_OS
    path('os/', views.ordemservicos_index, name='ordemservicos_index'),
    path('os/edit/<int:pk>', views.ordemservicos_edit, name='ordemservicos_edit'),
    path('os/add/', views.ordemservicos_add, name='ordemservicos_add'),
    path('os/detail/<int:pk>', views.ordemservicos_detail, name='ordemservicos_detail'),
    path('os/delete/<int:pk>', views.ordemservicos_delete, name='ordemservicos_delete'),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from apps.core import views as main_views
from ajax_select import urls as ajax_select_urls
from qr_code import urls as qr_code_urls
from apps.api.router import router


urlpatterns = [
    # Dashboard Principal
    path('', main_views.dashboard, name='dashboard'),

    # ADMIN: Apenas para administradores
    path('ediclei/', admin.site.urls),

    # APP: Core (Principal)
    path('core/', include('apps.core.urls')),

    # APPS: Local
    path('colaboradores/', include('apps.colaboradores.urls')),
    path('empregador/', include('apps.empregador.urls')),
    path('dispositivos/', include('apps.dispositivos.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('servicos/', include('apps.servicos.urls')),
    path('pdf/', include('apps.pdf.urls')),

    # API
    path('api/', include('apps.api.urls')),

    path('ajax_select/', include(ajax_select_urls)),
    path('qr_code/', include(qr_code_urls, namespace="qr_code")),


]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/clientes/models.py
from django.db import models
from apps.core.models import Pessoa


#  ======================================== MODELO_CONTRATADO ================================================
class Cliente(Pessoa):
    #  basicas
    cliente_id = models.AutoField(db_column='cliente_id', auto_created=True, primary_key=True,
                                  unique=True, null=False, serialize=False)

    class Meta:
        ordering = ['pes_nome']
        db_table = 'CLIENTES'
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def __str__(self):
        return self.pes_nome

apps/core/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


# Classe controle token login rest-framework
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


# Classe controle de data/hora de criacao e modificacao.
class TimeStamped(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# Classe controle se foi visualizado ou nao.
class Displayable(models.Model):
    class Meta:
        abstract = True

    status = models.BooleanField(default=True)


#  ========================================= MODELO_PESSOA ===================================================
class Pessoa(TimeStamped, Displayable):
    pes_id = models.AutoField(db_column='pes_id', primary_key=True, unique=True, null=False, serialize=False)
    pes_nome = models.CharField(db_column='pes_nome', null=False, blank=False, max_length=80)
    pes_cpf = models.CharField(db_column='pes_cpf', null=True, blank=True, max_length=11)
    pes_rg = models.CharField(db_column='pes_rg', null=True, blank=True, max_length=20)
    pes_telefone = models.CharField(db_column='pes_telefone', null=True, blank=True, max_length=16)
    pes_celular = models.CharField(db_column='pes_celular', null=True, blank=True, max_length=17)
    pes_email = models.CharField(db_column='pes_email', null=True, blank=True, max_length=50)

    class Meta:
        ordering = ['-pes_id']
        db_table = 'PESSOAS'

    def __str__(self):
        return self.pes_nome

apps/clientes/forms.py
# Django
from django import forms

# Local imports
from .models import Cliente


class ClienteForm(forms.ModelForm):
    pes_nome = forms.CharField(required=True, max_length=80,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    pes_cpf = forms.CharField(required=False, max_length=14,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    pes_rg = forms.CharField(required=False, max_length=20,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))
    pes_telefone = forms.CharField(required=False, max_length=16)
    pes_celular = forms.CharField(required=True, max_length=17)
    pes_email = forms.EmailField(required=False, widget=forms.EmailInput(attrs={'class': 'form-control'}))

    #  Uma classe inline para fornecer informações adicionais no formulário.
    class Meta:
        #  Fornecer uma associação entre ModelForm e um modelo
        model = Cliente
        fields = ('pes_nome', 'pes_cpf',
                  'pes_celular', 'pes_email',
                  'pes_rg', 'pes_telefone',)

apps/clientes/views.py
# Django imports
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone

# Local
from .models import Cliente
from .forms import ClienteForm
from apps.dispositivos.models import Dispositivo

# Terceiros
import sweetify


# CLIENTE_ADD =======================================================================================
@login_required(login_url='/core/sign-in/')
def clientes_add(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST or None)
        if not form.is_valid():
            sweetify.error(request, 'Ha algum erro no preenchimento dos campos!', persistent='OK')
            return render(request, 'clientes/cliente_add.html', {'form': form})
        model_instance = form.save(commit=False)
        model_instance.timestamp = timezone.now()
        model_instance.save()
        sweetify.success(request, 'Cliente cadastrado com sucesso!')
        return HttpResponseRedirect(reverse('dispositivos:dispositivos_add'))
    else:
        form = ClienteForm()
        return render(request, 'clientes/cliente_add.html', {'form': form})


# CLIENTE_EDIT =======================================================================================
@login_required(login_url='/core/sign-in/')
def clientes_edit(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == "POST":
        form = ClienteForm(request.POST, instance=cliente)
        if not form.is_valid():
            sweetify.error(request, 'Ha algum erro no preenchimento dos campos!', persistent='OK')
            return render(request, 'clientes/cliente_edit.html', {'form': form})
        cliente = form.save(commit=False)
        cliente.timestamp = timezone.now()
        cliente.save()
        sweetify.success(request, 'Editado com Sucesso!')
        return HttpResponseRedirect(reverse('clientes:clientes_detail', args=(cliente.pk,)))
    else:
        form = ClienteForm(instance=cliente)

    args = {'form': form, 'clientes': cliente}
    return render(request, 'clientes/cliente_edit.html', args)


# CLIENTE_DELETE ======================================================================================
def clientes_delete(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    cliente.delete()
    sweetify.success(request, 'Cliente deletado com sucesso!')

    return redirect('/clientes')


# CLIENTE_DETAIL ======================================================================================
@login_required(login_url='/core/sign-in/')
def clientes_detail(request, pk):
    msg = messages.get_messages(request)
    cliente = get_object_or_404(Cliente, pk=pk)

    args = {'cliente': cliente, 'message': msg}
    return render(request, 'clientes/cliente_detail.html', args)


# CLIENTE_INDEX =======================================================================================
@login_required(login_url='/core/sign-in/')
def clientes_index(request):
    user = getattr(request, 'user', None)
    cliente_list = Cliente.objects.all()
    paginator = Paginator(cliente_list, 5)  # Exibir 10 objetos por pagina

    page = request.GET.get('page')
    try:
        clientes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        clientes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        clientes = paginator.page(paginator.num_pages)

    return render(request, 'clientes/cliente_list.html', {'clientes': clientes, 'user': user})

apps/core/views.py
#  Django
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render, redirect

# local
from apps.servicos.models import OrdemServico

#  Terceiros
import sweetify


#  DASHBOARD_PRINCIPAL ===============================================================================
@login_required(login_url='/core/sign-in/')
def dashboard(request):
    storage = messages.get_messages(request)
    user = getattr(request, 'user', None)

    hoje = datetime.date.today()

    os_abertas = OrdemServico.objects.filter(Q(status=1)).count()
    os_prontas = OrdemServico.objects.filter(Q(status=8)).count()
    os_entregues = OrdemServico.objects.filter(Q(status=9)).count()
    os_atrasadas = OrdemServico.objects.filter(created_at__day=-30 + hoje.day).count()

    args = {'user': user, 'message': storage, 'os_abertas': os_abertas,
            'os_prontas': os_prontas, 'os_atradadas': os_atrasadas, 'os_entregues': os_entregues}
    return render(request, 'core/dashboard.html', args)


#  ===================================================================================================


#  LOGIN_USER =======================================================================================
def login_user(request):
    if not request.method == 'POST':
        return render(request, 'core/sign_in.html')
    user = authenticate(username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect('/')
    sweetify.error(request, 'Usuário ou Senha inválidos!', persistent='OK')
    return render(request, 'core/sign_in.html')
#  ===================================================================================================


#  LOGOUT_USER =======================================================================================
def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return render(request, 'core/sign_in.html')
#  ===================================================================================================

apps/core/templates/clientes/cliente_detail.html
{% extends 'core/base.html' %}
{% load static %}

  {% block toolbar %}
      <div class="toolbar">
         <ol class="breadcrumb breadcrumb-transparent nm">
             <li><a href="/">Desktop</a></li>
             <li><a href="{% url 'clientes:clientes_index' %}">Clientes</a></li>
             <li class="active">Visualizando Cliente</li>
          </ol>
       </div>
  {% endblock %}

{% block content %}

    <!-- Page Header -->
    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked">
                <li>
                    <a href="{% url 'clientes:clientes_index' %}">Todos os Clientes</a>
                </li>
                <li>
                    <a href="{% url 'dispositivos:dispositivos_index' %}">Dispositivos</a>
                </li>
                <li>
                    <a href="{% url 'servicos:ordemservicos_index' %}">Ordem de Serviço</a>
                </li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title ellipsis">ID: {{ cliente.pk }}</h3>
                    <div class="panel-toolbar text-right">
                        <a class="btn btn-default" href="{% url 'clientes:clientes_edit' pk=cliente.pk %}"><span
                                class="ico-pencil6"></span> Editar</a>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Mais
                                <span class="caret"></span></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a id="bt-registro" href="{% url 'clientes:clientes_add' %}">Cadastrar Novo</a></li>
                                <li>
                                    <a href="#">
                                        <span class="text">Ordens Serviço</span>
                                        <span class="number">
		                    			<span class="label label-success">0</span>
		                    			</span>
                                    </a>
                                </li>
                                <li><a id="bt-opces" href="#">Dispositivos Relacionados</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"><span class="ico-trash"></span> Deletar</button>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tbody class="visualizacao-corpo">
                        <tr>
                            <td>Nome</td>
                            <td>{{ cliente.pes_nome }}</td>
                        </tr>
                        <tr>
                            <td>Telefone</td>
                            <td>{{ cliente.pes_telefone }}</td>
                        </tr>
                        <tr>
                            <td>Celular</td>
                            <td>{{ cliente.pes_celular }}</td>
                        </tr>
                        <tr>
                            <td>CPF</td>
                            <td>{{ cliente.pes_cpf }}</td>
                        </tr>
                        <tr>
                            <td>RG</td>
                            <td>{{ cliente.pes_rg }}</td>
                        </tr>
                        <tr>
                            <td>E-mail</td>
                            <td>{{ cliente.pes_email }}</td>
                        </tr>
                        <tr>
                            <td>CPF</td>
                            <td>{{ cliente.pes_cpf }}</td>
                        </tr>
                        <tr>
                            <td>Data do Cadastro</td>
                            <td>{{ cliente.created_at }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Painel Dispositivos -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title panel-title-mini">Dispositivos</h4>
                    <div class="panel-toolbar text-right">

                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-stripped table-hover">
                        <thead>
                        <tr>
                            <th class="col-table-1">ID</th>
                            <th class="col-table-1">Marca</th>
                            <th class="col-table-1">Modelo</th>
                            <th class="col-table-1">IMEI</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if cliente.dispositivo_set %}
                            {% for dispositivo in cliente.dispositivo_set.select_related %}
                            <tr>
                                <td>
                                    <a href="{% url 'dispositivos:dispositivos_detail' pk=dispositivo.pk %}">{{ dispositivo.pk }}</a><br>
                                <td>
                                    {{ dispositivo.modelo }}
                                </td>
                                <td>
                                    {{ dispositivo.marca }}
                                <td>
                                    {{ dispositivo.imei }}
                            </tr>
                            {% endfor %}
                        {% else %}
                            <td>Nenhum dispositivo vinculado a este cliente</td>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!--./ Painel Dispositivos -->

        <!-- Painel Ordem de Servico -->
        <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title panel-title-mini">Histórico</h4>
                    <div class="panel-toolbar text-right">

                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-stripped table-hover">
                        <thead>
                        <tr>
                            <th class="col-table-1">Data/Hora</th>
                            <th class="col-table-1">O.S</th>
                            <th class="col-table-1">Status</th>
                            <th class="col-table-6">Descrição</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>20/05/18 08:50hrs</td>
                            <td>1001</td>
                            <td>Aberta</td>
                            <td>Aparelho com tela trincada. Muitos arranhões. Sem carregador.</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!--./ Painel Dispositivos -->


        </div>
    </div>


    <!-- Modal Delete -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Confirmação</h4>
                </div>
                <div class="modal-body">
                    <h4>Tem certeza que deseja deletar o cliente???</h4><br>
                    <h4>Nome: {{ cliente.pes_nome }}</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a id="btn-excluir"
                       class="btn btn-danger"
                       href="{% url 'clientes:clientes_delete' pk=cliente.pk %}">Deletar</a>
                </div>
            </div>
        </div>
    </div>
    <!-- ...Modal Delete -->





{% endblock %}

{% block javascript %}
  <script>
    $(document).on('click', ':not(form)[data-confirm]', function(e){
      if(!confirm($(this).data('confirm'))){
          e.stopImmediatePropagation();
          e.preventDefault();
      }
    });
  </script>
{% endblock %}

apps/core/templates/clientes/cliente_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    <h4 class="title semibold">Clientes</h4>
{% endblock %}

{% block toolbar %}
    <div class="toolbar">
        <ol class="breadcrumb breadcrumb-transparent nm">
            <li><a href="/">Desktop</a></li>
            <li class="active">Clientes</li>
        </ol>
    </div>
{% endblock %}

{% block content %}



    <!-- Page Header -->
    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked">
                <li class="active">
                    <a href="{% url 'clientes:clientes_index' %}">Clientes</a>
                </li>
                <li>
                    <a href="{% url 'dispositivos:dispositivos_index' %}">Dispositivos</a>
                </li>
                <li>
                    <a href="{% url 'servicos:ordemservicos_index' %}">Ordem de Serviço</a>
                </li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h3 class="panel-title ellipsis">Todos os clientes</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-4 form-group">
                            <input id="buscaNome" type="text" placeholder="Buscar por nome"
                                   class="form-control filtro">
                        </div>
                        <div class="col-sm-8 form-group" align="right"><a class="btn btn-success" href="{% url 'clientes:clientes_add' %}"><span
                                class="glyphicon glyphicon-plus"></span> Adicionar</a></div>
                    </div>

                    <div id="tabela-clientes">
                        <div class="table-responsive">


                            <table class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nome</th>
                                    <th>Celular</th>
                                    <th>Últ. Atualização</th>
                                    <th></th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for cliente in clientes %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'clientes:clientes_detail' pk=cliente.pk %}">{{ cliente.pk}}</a><br>
                                        </td>
                                        <td>
                                            {{ cliente.pes_nome|upper }}
                                        </td>

                                        <td>
                                        {{ cliente.pes_celular }}
                                        </td>
                                        <td>
                                            {{ cliente.updated_at|date:'d/m/y H:i' }}
                                        <td>
                                            <a class="btn btn-default btn-sm" href="{% url 'clientes:clientes_edit' pk=cliente.pk %}"><span class="ico-pencil6"></span></a>
                                            <a class="btn btn-info btn-sm" href="{% url 'clientes:clientes_detail' pk=cliente.pk %}"><span class="ico-eye-open"></span></a>
                                        </td>
                                    </tr>

                                {% endfor %}
                                </tbody>
                            </table>

                        </div>

                         <!-- Paginacao -->
                        <div class="row">
                            <div class="col-sm-12">
                                {% if clientes.has_other_pages %}
                                    <ul class="pagination">
                                        {% if clientes.has_previous %}
                                            <li class="active">
                                                <a href="?page={{ clientes.previous_page_number }}"
                                                   aria-label="Anterior">
                                                    <span class="glyphicon glyphicon-chevron-left"></span> Anterior
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="disabled">
                                                <a href="#" aria-label="Anterior">
                                                    <span class="glyphicon glyphicon-chevron-left"></span> Anterior
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% for i in clientes.paginator.page_range %}
                                            {% if clientes.number == i %}
                                                <li class="active"><a href="javascript:void(0);">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if clientes.has_next %}
                                            <li class="enabled">
                                                <a href="?page={{ clientes.next_page_number }}"
                                                   aria-label="Próximo">
                                                    <span class="glyphicon glyphicon-chevron-right"></span> Próximo
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="disabled">
                                                <a href="javascript:void(0);" aria-label="Próximo">
                                                    <span class="glyphicon glyphicon-chevron-right"></span> Próximo
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                        <!--./ Paginacao -->

                    </div>
                </div>
            </div>

        </div>
    </div>



{% endblock %}