apps/clientes/urls.py
# Django
from django.urls import include, path

# Views Dispositivos
from . import views

app_name = 'clientes'
urlpatterns = [

    # CAD_Clientes
    path('', views.clientes_index, name='clientes_index'),
    path('edit/<int:pk>', views.clientes_edit, name='clientes_edit'),
    path('add', views.clientes_add, name='clientes_add'),
    path('detail/<int:pk>', views.clientes_detail, name='clientes_detail'),
    path('delete/<int:pk>', views.clientes_delete, name='clientes_delete'),
]

apps/core/urls.py
# Django
from django.urls import path, include
from django.contrib.auth import views as auth_views

# Rest-Framework
from rest_framework.authtoken import views as rest_framework_views

# Views Core
from . import views

app_name = 'core'
urlpatterns = [

    #  Login / Logout
    path('sign-in/', views.login_user, name='sign-in'),
    path('sign-out/', views.logout_view, name='sign-out'),

    # Token Rest-Framework
    path('get_auth_token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
    path('rest-auth/', include('rest_auth.urls')),
]

apps/dispositivos/urls.py
# Django
from django.urls import include, path

# Views Dispositivos
from . import views

app_name = 'dispositivos'
urlpatterns = [

    # CAD_Dispositivos
    path('', views.dispositivos_index, name='dispositivos_index'),
    path('edit/<int:pk>', views.dispositivos_edit, name='dispositivos_edit'),
    path('add', views.dispositivos_add, name='dispositivos_add'),
    path('detail/<int:pk>', views.dispositivos_detail, name='dispositivos_detail'),
    path('delete/<int:pk>', views.dispositivos_delete, name='dispositivos_delete'),
]

apps/servicos/urls.py
# Django
from django.urls import include, path

# Views Servicos
from . import views

app_name = 'servicos'
urlpatterns = [

    # CAD_OS
    path('os/', views.ordemservicos_index, name='ordemservicos_index'),
    path('os/edit/<int:pk>', views.ordemservicos_edit, name='ordemservicos_edit'),
    path('os/add/', views.ordemservicos_add, name='ordemservicos_add'),
    path('os/detail/<int:pk>', views.ordemservicos_detail, name='ordemservicos_detail'),
    path('os/delete/<int:pk>', views.ordemservicos_delete, name='ordemservicos_delete'),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from apps.core import views as main_views
from ajax_select import urls as ajax_select_urls
from qr_code import urls as qr_code_urls
from apps.api.router import router


urlpatterns = [
    # Dashboard Principal
    path('', main_views.dashboard, name='dashboard'),

    # ADMIN: Apenas para administradores
    path('ediclei/', admin.site.urls),

    # APP: Core (Principal)
    path('core/', include('apps.core.urls')),

    # APPS: Local
    path('colaboradores/', include('apps.colaboradores.urls')),
    path('empregador/', include('apps.empregador.urls')),
    path('dispositivos/', include('apps.dispositivos.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('servicos/', include('apps.servicos.urls')),
    path('pdf/', include('apps.pdf.urls')),

    # API
    path('api/', include('apps.api.urls')),

    path('ajax_select/', include(ajax_select_urls)),
    path('qr_code/', include(qr_code_urls, namespace="qr_code")),


]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/core/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


# Classe controle token login rest-framework
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


# Classe controle de data/hora de criacao e modificacao.
class TimeStamped(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# Classe controle se foi visualizado ou nao.
class Displayable(models.Model):
    class Meta:
        abstract = True

    status = models.BooleanField(default=True)


#  ========================================= MODELO_PESSOA ===================================================
class Pessoa(TimeStamped, Displayable):
    pes_id = models.AutoField(db_column='pes_id', primary_key=True, unique=True, null=False, serialize=False)
    pes_nome = models.CharField(db_column='pes_nome', null=False, blank=False, max_length=80)
    pes_cpf = models.CharField(db_column='pes_cpf', null=True, blank=True, max_length=11)
    pes_rg = models.CharField(db_column='pes_rg', null=True, blank=True, max_length=20)
    pes_telefone = models.CharField(db_column='pes_telefone', null=True, blank=True, max_length=16)
    pes_celular = models.CharField(db_column='pes_celular', null=True, blank=True, max_length=17)
    pes_email = models.CharField(db_column='pes_email', null=True, blank=True, max_length=50)

    class Meta:
        ordering = ['-pes_id']
        db_table = 'PESSOAS'

    def __str__(self):
        return self.pes_nome

apps/core/views.py
#  Django
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render, redirect

# local
from apps.servicos.models import OrdemServico

#  Terceiros
import sweetify


#  DASHBOARD_PRINCIPAL ===============================================================================
@login_required(login_url='/core/sign-in/')
def dashboard(request):
    storage = messages.get_messages(request)
    user = getattr(request, 'user', None)

    hoje = datetime.date.today()

    os_abertas = OrdemServico.objects.filter(Q(status=1)).count()
    os_prontas = OrdemServico.objects.filter(Q(status=8)).count()
    os_entregues = OrdemServico.objects.filter(Q(status=9)).count()
    os_atrasadas = OrdemServico.objects.filter(created_at__day=-30 + hoje.day).count()

    args = {'user': user, 'message': storage, 'os_abertas': os_abertas,
            'os_prontas': os_prontas, 'os_atradadas': os_atrasadas, 'os_entregues': os_entregues}
    return render(request, 'core/dashboard.html', args)


#  ===================================================================================================


#  LOGIN_USER =======================================================================================
def login_user(request):
    if not request.method == 'POST':
        return render(request, 'core/sign_in.html')
    user = authenticate(username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect('/')
    sweetify.error(request, 'Usuário ou Senha inválidos!', persistent='OK')
    return render(request, 'core/sign_in.html')
#  ===================================================================================================


#  LOGOUT_USER =======================================================================================
def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return render(request, 'core/sign_in.html')
#  ===================================================================================================

apps/core/templates/core/base.html
<!DOCTYPE html>
<html lang="pt-br">
    {% load static %}
  <head>
    <meta name="language" content="pt-BR" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

    <meta name="description" content="Gestao em Assistência Técnica">

    <title>SysMobile | Excelência</title>

       <!-- START STYLESHEETS -->
        <script type="text/javascript" src="{% static 'js/pace.min.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/athom.css' %}">

        <!-- Application stylesheet : mandatory -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        <link rel="stylesheet" href="{% static 'css/uielement.css' %}">
        <link rel="stylesheet" href="{% static 'css/gritter.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">

        <link rel="stylesheet" href="{% static 'css/select2.css' %}">
      <link href="{% static 'vendor/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet">
        <!--/ Application stylesheet -->

        <!-- CSS EXTRA -->
        {% block css %}
        {% endblock %}
        <!--/ CSS EXTRA -->

		<!-- modernizr script -->
        <script type="text/javascript" src="{% static 'js/modernizr-custom.js' %}"></script>
        <!--/ modernizr script -->
        <!-- END STYLESHEETS -->

      <!-- Fav icons -->
    <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" href="{% static 'img/favicon.png' %}">
      {{ form.media }}
  </head>

<!-- START Body -->
    <body>
    	<div>
		<!-- START Template Header -->
        <header id="header" class="navbar">
            <!-- START navbar header -->
            <div class="navbar-header">
                <!-- Brand -->
                <a class="navbar-brand" href="/">
                    <span class="logo-figure"></span>
                    <span class="logo-text"></span>
                </a>
                <!--/ Brand -->
            </div>
            <!--/ END navbar header -->

            <!-- START Toolbar -->
            <div class="navbar-toolbar clearfix">
                <!-- START Left nav -->
                <ul class="nav navbar-nav navbar-left">
                    <!-- Sidebar shrink -->
                    <li class="hidden-xs hidden-sm hidden-md">
                        <a href="javascript:void(0);" class="sidebar-minimize" data-toggle="minimize" title="Minimizar menu lateral">
                            <span class="meta">
                                <span class="icon"></span>
                            </span>
                        </a>
                    </li>
                    <!--/ Sidebar shrink -->

                    <!-- Offcanvas left: This menu will take position at the top of template header (mobile only). Make sure that only #header have the `position: relative`, or it may cause unwanted behavior -->
                    <li class="navbar-main hidden-lg hidden-md hidden-sm">
                        <a href="javascript:void(0);" data-toggle="sidebar" data-direction="ltr" rel="tooltip" title="Menu Lateral">
                            <span class="meta">
                                <span class="icon"><i class="ico-paragraph-justify3"></i></span>
                            </span>
                        </a>
                    </li>
                    <!--/ Offcanvas left -->
                </ul>
                <!--/ END Left nav -->
			    <!-- START Right nav -->
                <ul class="nav navbar-nav navbar-right">
					<!-- Notification dropdown -->
                    <li class="step3" >
                        <a target="_blank" href="#">
                            <span class="meta">
                               <!-- <span class="icon"><i class="ico-question"></i></span> -->
                            </span>
                        </a>
                    </li>
                    <!--/ Notification dropdown -->

                    <!-- Profile dropdown -->
                    <li class="dropdown profile step4">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="meta">
                                <span class="text hidden-xs hidden-sm pl5">{{ user.first_name}}</span>
                                <span class="avatar">
                                	<img src="{% static 'image/icons/avatar.png' %}" class="img-circle" alt="" />
                                </span>
                            </span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                            	<a href="#"><span class="icon"><i class="ico-user-plus2"></i></span> Gerenciar Usuários</a>
                            </li>
                            <li>
                            	<a href="#"><span class="icon"><i class="ico-cog4"></i></span> Configurações</a>
                            </li>
                            <li>
                            	<a href="#"><span class="icon"><i class="ico-dashboard2"></i></span> Conta</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="{% url 'core:sign-out' %}"><span class="icon"><i class="ico-exit"></i></span> Sair</a>
                            </li>
                        </ul>
                    </li>
                    <!-- Profile dropdown -->
				</ul>
                <!--/ END Right nav -->
            </div>
            <!--/ END Toolbar -->
        </header>
        </div>
        <aside class="sidebar sidebar-left sidebar-menu">
            <!-- START Sidebar Content -->
            <section class="content slimscroll">
                <!-- START Template Navigation/Menu -->
                <ul class="topmenu topmenu-responsive" data-toggle="menu">
                    <li class="active">
                        <a href="/" data-target="#desktop" data-parent=".topmenu">
                            <span class="figure"><i class="ico-home2"></i></span>
                            <span class="text">Desktop</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'clientes:clientes_index' %}" data-parent=".topmenu">
                            <span class="figure"><i class="ico-users"></i></span>
                            <span class="text">Clientes</span>
                        </a>
                    </li>

                    <li >
                        <a href="{% url 'dispositivos:dispositivos_index' %}" data-parent=".topmenu">
                            <span class="figure"><i class="ico-mobile"></i></span>
                            <span class="text">Dispositivos</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'servicos:ordemservicos_index' %}" data-parent=".topmenu">
                            <span class="figure"><i class="ico-clipboard4"></i></span>
                            <span class="text">Ordem Serviço</span>
                        </a>
                    </li>

                    <li >
                        <a href="{% url 'core:sign-out' %}" data-parent=".topmenu">
                            <span class="figure"><i class="ico-exit3"></i></span>
                            <span class="text">Sair</span>
                        </a>
                    </li>
                </ul>
                <!--/ END Template Navigation/Menu -->
            </section>
            <!--/ END Sidebar Container -->
        </aside>

	    <section id="main" role="main">
            <!-- START Template Container -->
            <div class="container-fluid">
                <!-- Page Header -->
                <div class="page-header page-header-block">
                    <div class="page-header-section">

                        <!-- Titulo -->
                        {% block titulo %}
                        {% endblock %}
                        <!--/ Titulo -->
                    </div>
                    <div class="page-header-section">

                        <!-- Toolbar -->
                        {% block toolbar %}
                        {% endblock %}
                        <!--/ Toolbar -->
                    </div>
                </div>

            {% block content %}
            {% endblock %}


        </div>
        </section>

    <div>
    <!-- START Template Footer -->
        <footer id="footer" class="rodape">
            <!-- START container-fluid -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <!-- copyright -->
                        <p class="nm text-muted">&copy; SysMobile 2018. Todos os direitos reservados.</p>
                        <!--/ copyright -->
                    </div>
                    <div class="col-sm-6 text-right hidden-xs">
                        <a target="_blank" href="#" class="semibold">Política de Privacidade</a>
                        <span class="ml5 mr5">&#8226;</span>
                        <a target="_blank" href="#" class="semibold">Termo de Serviços</a>
                    </div>
                </div>
            </div>
            <!--/ END container-fluid -->
        </footer>
        <!--/ END Template Footer -->
        </div>


    <!-- Scripts -->
        <script type="text/javascript" src="{% static 'js/vendor.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/core.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/select2/select2.min.js' %}"></script>

        <script src="{% static 'js/select2/i18n/pt-BR.js' %}" type="text/javascript"></script>

    <!--/ Application and vendor script : mandatory -->
        <script src="{% static 'vendor/sweetalert2/sweetalert2.min.js' %}"></script>



    <!-- Sweet Alert -->
    {% load sweetify %}
    {% sweetify %}

    {% block javascript %}
    {% endblock %}

  </body>

</html>

apps/core/templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}

    {% now "H" as current_time %}

    {% if current_time > 12 and current_time <= 18 %}
         <h4 class="title">Boa tarde, {{ user.first_name }}!</h4>
    {% elif current_time >= 6 and current_time <= 12 %}
        <h4 class="title">Bom dia, {{ user.first_name }}!</h4>
    {% else %}
        <h4 class="title">Boa noite, {{ user.first_name }}!</h4>
    {% endif %}

{% endblock %}


{% block content %}

    <!-- Linha 0 Dasboard -->
    <div class="row">
        <div class="col-md-4">
            <h2>Busca rápida</h2>
            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <select id="busca" class="form-control js-data-example-ajax input-lg">
                    </select>
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
    <br>

    </div>
    <!--./ Linha 0 Dasboard -->
    <div class="row">
        <div class="col-md-4"></div>
    </div>


        <!-- Linha 1 Dasboard -->
        <div class="row">

            <!-- Coluna 1 Dasboard -->
            <div class="col-md-4">

                <!-- Panel Cliente -->
                <div class="panel panel-danger">
                    <div class="panel-heading" align="center">
                        CLIENTE / DISPOSITIVO
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">

                                <!-- Add Cliente -->
                                <div class="col-xs-6 col-sm-4">
                                    <div class="div-square">
                                        <a href="{% url 'clientes:clientes_add' %}">
                                            <img alt="Add Cliente" style="width: 76px; height: 76px;"
                                                 src="{% static 'image/icons/add-cliente.png' %}">
                                            <h4>Add Cliente</h4>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <!-- Add Dispositivo -->
                                <div class="col-xs-6 col-sm-4">
                                    <div class="div-square">
                                        <a href="{% url 'dispositivos:dispositivos_add' %}">
                                            <img alt="Pesquisar Dispositivo" style="width: 76px; height: 76px;"
                                                 src="{% static 'image/icons/add-dispositivo.png' %}">
                                            <h4>Add Dispositivo</h4>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--./ Panel Cliente -->

                <!--./ Coluna 1 Dashboard -->
            </div>

            <!-- Coluna 2 Dashboard -->
             <div class="col-md-4">
                     <!-- Panel Ordem Servico -->
                <div class="panel panel-danger">
                    <div class="panel-heading" align="center">
                        ORDEM SERVIÇO
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">

                                <!-- Add OS -->
                                <div class="col-xs-6 col-sm-4">
                                    <div class="div-square">
                                        <a href="{% url 'servicos:ordemservicos_add' %}">
                                            <img alt="Add O.S" style="width: 76px; height: 76px;"
                                                 src="{% static 'image/icons/add-os.png' %}">
                                            <h4>Criar Nova</h4>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <!-- Pesquisa OS -->
                                <div class="col-xs-6 col-sm-4">
                                    <div class="div-square">
                                        <a href="{% url 'servicos:ordemservicos_index' %}">
                                            <img alt="Pesquisa O.S" style="width: 76px; height: 76px;"
                                                 src="{% static 'image/icons/pesquisa-os.png' %}">
                                            <h4>Pesquisar</h4>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <br>
                        </div>
                    </div>
                </div>
                <!--./ Panel Ordem Servico -->

             </div>
            <!--./ Coluna 2 Dashboard -->

            <!-- Coluna 3 Dasboard -->
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title titulo-pequeno"><i class="ico-bar-chart mr5"></i>Índices Atuais</h5>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><i class="ico-circle mr5 text-success"></i>O.S Entregues
                            <span class="semibold pull-right">{{ os_entregues }}</span></li>
                        <li class="list-group-item"><i class="ico-circle mr5 text-primary"></i>O.S Prontas
                            <span class="semibold pull-right">{{ os_prontas }}</span></li>
                        <li class="list-group-item"><i class="ico-circle mr5 text-danger"></i>O.S Abertas
                            <span class="semibold pull-right">{{ os_abertas }}</span></li>
                        <li class="list-group-item"><i class="ico-circle mr5 text-error"></i>Prazo Encerrado
                            <span class="semibold pull-right">{{ os_atradadas }}</span></li>
                    </ul>
                </div>
            </div>
            <!--./ Clouna 3 Dasboard -->

            <!--./ Linha 1 Dasboard -->
        </div>



{% endblock %}

{% block javascript %}
    <script>


        $('#busca').select2({
            language: 'pt-BR',
            ajax: {
                url: "/api/busca/",
                 dataType: 'json',
                delay: 250,

                data: function (params) {
                    return {
                        q: params.term, // search term
                        page: params.page
                    };
                },
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {

                            if (item.cliente.pes_nome !== null) {
                                item.cliente.pes_nome = item.cliente.pes_nome.toUpperCase()
                            }
                            if (item.hospedagem !== null) {
                                item.hospedagem = item.hospedagem.toUpperCase()
                            }else {
                                item.hospedagem = "Local: ???"
                            }

                            if(typeof item.cliente.id === "undefined" && item.cliente.id === null) {
                                item.cliente.id = 0
                            }

                            return {

                                id: item.os_id,
                                text: "Cliente: " + item.cliente.pes_nome + ", &nbsp;" + item.hospedagem,

                                results: data.items
                            }
                        })
                    };
                },
                cache: true
            },
            escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
            minimumInputLength: 2,
            maximumInputLength: 11,
            placeholder: 'QRcode, cliente, cpf, hospedagem...',
            templateResult: formatResult

        }).on('select2:select', function (e) {

                if(typeof e.params.data.id !== "undefined" && e.params.data.id !== null) {
                    window.location.replace("/servicos/os/detail/" + e.params.data.id);
                }
        });

        function formatResult (item) {
            if (item.loading) {
                return item.text;
            }
                return '<div class="dropdown-item"> O.S: #' +
                        item.id + '</div><span>' + item.text + '</div>';

            }

    </script>
{% endblock %}

apps/core/templates/core/sign_in.html
{% extends 'core/base_signup.html' %}
{% load static %}

{% block content %}

         	<section id="main" role="main">
	    	<section class="container">
                <!-- START row -->
                <div class="row">
                    <div class="col-lg-4 col-lg-offset-4">
                        <div class="text-center row" style="margin-bottom:20px;">
                        	<div class="col-xs-12">
                        		<a href="http://excelenciacell.com" class="link-logo-central">
		                        	<img class="center-block img-responsive" src="{% static 'image/logo/logo-text.png' %}" />
                        		</a>
	                        	<h5 class="semibold text-muted mt-5">Bem vindo de volta.</h5>
                        	</div>
                        </div>

                        <hr><!-- horizontal line -->


                        <!-- Login form -->
                        <form id="form-login" class="panel" name="form-login" method="post" action="{% url 'core:sign-in' %}" accept-charset="ISO-8859-1" data-parsley-validate>
                             {% csrf_token %}
                            <div class="panel-body">
                                <div class="form-group">
                                    <div class="form-stack has-icon pull-left">
                                        <input type="text" class="form-control input-lg" id="login_username" name="username" placeholder="Usuário" data-parsley-errors-container="#error-container" data-parsley-error-message="Por favor digite seu nome de usuário" data-parsley-required autofocus="autofocus">
                                        <i class="ico-envelop form-control-icon"></i>
                                    </div>
                                    <div class="form-stack has-icon pull-left">
                                        <input id="login_password" name="password" type="password" class="form-control input-lg" placeholder="Senha" data-parsley-errors-container="#error-container" data-parsley-error-message="Por favor digite sua senha" data-parsley-required>
                                        <i class="ico-lock2 form-control-icon"></i>
                                    </div>
                                </div>
								<div id="error-container" class="mb15">
                                     {% if form.errors %}
                                        <p class=" label label-danger">
                                            Usuário ou Senha incorretos!
                                            Tente novamente.
                                        </p>
                                         <div class="clearfix"></div>
                                     {% endif %}
                                    {% if next %}
                                        {% if user.is_authenticated %}
                                            <p>Sua conta não tem acesso a esta página. Para prosseguir,
                                                 Faça login com uma conta que tenha acesso.</p>
                                        {% else %}
                                            <p>Faça o login para ver esta página.</p>
                                        {% endif %}
                                    {% endif %}
                                </div>

								<div class="form-group">
                                    <div class="row">
                                        <div class="col-xs-12 text-right">
                                            <a href="#">Esqueceu a senha?</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group nm">
                                    <button id="btn-entrar" type="submit" class="btn btn-block btn-success"><span class="semibold">Entrar</span></button>
                                </div>
                            </div>
                        </form>
                        <!-- Login form -->

                        <hr><!-- horizontal line -->

                        <p class="text-muted text-center">&copy; SysMobile 2018. Todos os direitos reservados.</p>
                    </div>
                </div>
                <!--/ END row -->
            </section>
    	</section>


{% endblock %}